#!/bin/sh
#
# author: jzbor
#

. __LIB_FILE__ || exit 1

HELPTEXT="Converts a file (first argument) into a specified format (second argument)"
FOUT="$2"
load_file "$1"


# parse arguments
while :; do
    case $1 in
        -h | --help) print_help; exit ;;
        *) break ;;
    esac
done

check_dependencies pandoc
check_file

pandoc "$FILE" --pdf-engine=pdflatex -o "$FILEDIR/$BASENAME.$FOUT"
