#!/bin/bash
# From https://www.reddit.com/r/linuxquestions/comments/ham5i6/find_duplicate_files/
# Dependencies: find xargs

. __LIB_FILE__ || exit 1

HELPTEXT="Finds duplicates in the directory passed as first argument"


find_duplicates () {
    find "$1" -type f -print0 |
        xargs -0 stat -c "%012s"$'\t'"%n" |
        sort -k1,1n |
        uniq -w 12 -D |
        cut -f2 |
    while read f
    do
        md5sum "$f"
    done | sort | uniq -w 32 --all-repeated=separate
}


# parse arguments
while :; do
    case $1 in
        -h | --help) print_help; exit ;;
        *) break ;;
    esac
done

if [ "$1" = "" ]; then
    DIR="$(pwd)"
elif ! [ -d "$1" ]; then
    die "$1 is not a directory"
else
    DIR="$1"
fi

find_duplicates "$DIR"
