#!/bin/sh
#
# author: jzbor
#

. __LIB_FILE__ || exit 1

HELPTEXT="Open a file

    -h  --help      This help message
    -o  --output    Open output file of the given file"
OPENOUTPUT=0


open_output () {
    case $FILE in
        *.md | *.me | *.mom | *.ms | *.rmd | *.tex )
            if [ -f "$FILEDIR/$BASENAME.pdf" ]; then
                if env_is_set READER; then
                    $READER "$FILEDIR/$BASENAME.pdf"
                else
                    eprint "READER not set - falling back to xdg-open"
                    xdg-open "$FILEDIR/$BASENAME.pdf"
                fi
            elif [ -f "$FILEDIR/$BASENAME.html" ]; then
                if env_is_set BROWSER; then
                    $BROWSER "$FILEDIR/$BASENAME.html"
                else
                    eprint "BROWSER not set - falling back to xdg-open"
                    xdg-open "$FILEDIR/$BASENAME.html"
                fi
            else
                die "No output file found for $FILENAME"
            fi
            ;;
    esac
}

open_file () {
    if [ "$(file -i "$FILE" | cut -d' ' -f2 | sed 's/\/.*//')" = "text" ] \
            || [ "$(file -i "$FILE" | cut -d' ' -f2)" = "inode/x-empty;" ]; then
        $EDITOR "$FILE"
    else
        check_dependencies xdg-open
        xdg-open "$FILE"
    fi
}

# parse arguments
while :; do
    case $1 in
        -h | --help) print_help; exit ;;
        -o | --output) OPENOUTPUT=1; shift ;;
        *) break ;;
    esac
done

for f in "$@"; do
    load_file "$f"
    if [ "$OPENOUTPUT" = 1 ]; then
        open_output
    else
        open_file
    fi
done


