#!/bin/sh

. __LIB_FILE__ || exit 1

HELPTEXT="Refreshes mirrors of pacman based distros

    -e  --edit      Edit mirrorlist before ranking
    -m  --main      Only fetch main mirrors (no Arch mirrors on Artix)
    -h  --help      This help message"
TEMP_MIRRORLIST="${TEMP:-/tmp}/pacmirrorlist"
EDIT=0
MAIN_ONLY=0


manjaro () {
    print_header "Running Manjaro's pacman-mirrors"
    sudo pacman-mirrors --fasttrack || exit 1
}

regular () {
    print_header "Downloading mirrorlist [$REPOSITORY]"
    echo "Downloading from $MIRRORURL"
    curl -o "$TEMP_MIRRORLIST" "$MIRRORURL" || exit 1
    sed -i 's/#S/S/g' "$TEMP_MIRRORLIST" || exit 1

    if [ "$EDIT" = 1 ]; then
        ${EDITOR:?} "$TEMP_MIRRORLIST"
    fi

    print_header "Ranking mirrors"
    echo "This may take some while..."
    echo
    if [ "$REPOSITORY" = "arch" ]; then
        rankmirrors-arch -v "$TEMP_MIRRORLIST" | tee "$TEMP_MIRRORLIST.fastest" || exit 1
    else
        rankmirrors -v "$TEMP_MIRRORLIST" | tee "$TEMP_MIRRORLIST.fastest" || exit 1
    fi

    print_header "Replace current mirrorlist?"
    read -p "(y/N) " answer
    case $answer in
        y | Y | yes | Yes) ;;
        *) exit ;;
    esac
    sudo mv -v "$TEMP_MIRRORLIST.fastest" "${DEST:-/etc/pacman.d/mirrorlist}" || exit 1
}


# parse arguments
while :; do
    case $1 in
        -e | --edit) EDIT=1; shift ;;
        -m | --main) MAIN_ONLY=1; shift ;;
        -h | --help) print_help; exit ;;
        *) break ;;
    esac
done

. /etc/os-release \
    || die "No OS information available"

REPOSITORY="$ID"

case $ID in
    manjaro)
        manjaro
        ;;
    artix)
        MIRRORURL="https://gitea.artixlinux.org/packagesA/artix-mirrorlist/raw/branch/master/trunk/mirrorlist"
        regular
        if [ "$MAIN_ONLY" != 1 ]; then
            REPOSITORY="arch"
            MIRRORURL="https://archlinux.org/mirrorlist/all/https/"
            DEST="${DEST:-/etc/pacman.d/mirrorlist}-arch"
            regular
        fi
        ;;
    arch)
        MIRRORURL="https://archlinux.org/mirrorlist/all/https/"
        regular
        ;;
    *)
        die "Your distro seems to not be supported ($NAME)"
        ;;
esac

print_header "Update Pacman database and packages"
sudo pacman -Syyu
