#!/bin/sh

. __LIB_FILE__ || exit 1

HELPTEXT="Refreshes mirrors of pacman based distros

    -d  --dontreplace   Don't replace current mirrorlist
    -e  --edit          Edit mirrorlist before ranking
    -h  --help          This help message
    -m  --main          Only fetch main mirrors (no Arch mirrors on Artix)
    -r  --replace       Replace current mirrorlist"
TEMP_MIRRORLIST="${TEMP:-/tmp}/pacmirrorlist"
EDIT=0
MAIN_ONLY=0
REPLACE=0
DONT_REPLACE=0
REPOS_UPDATED=0


manjaro () {
    print_header "Running Manjaro's pacman-mirrors"
    check_dependencies pacman-mirrors sudo
    sudo pacman-mirrors --fasttrack || return
    REPOS_UPDATED=1
}

regular () {
    print_header "Downloading mirrorlist [$REPOSITORY]"
    check_dependencies curl
    echo "Downloading from $MIRRORURL"
    curl -o "$TEMP_MIRRORLIST" "$MIRRORURL" || exit 1

    if [ "$EDIT" = 1 ]; then
        ${EDITOR:?} "$TEMP_MIRRORLIST"
    else
        echo "Using all available mirrors for ranking"
        sed -i 's/#S/S/g' "$TEMP_MIRRORLIST" || exit 1
    fi

    print_header "Ranking mirrors"
    echo "This may take some while..."
    echo
    if [ "$REPOSITORY" = "arch" ]; then
        check_dependencies rankmirrors-arch
        rankmirrors-arch -v "$TEMP_MIRRORLIST" | tee "$TEMP_MIRRORLIST.fastest" || exit 1
    else
        check_dependencies rankmirrors
        rankmirrors -v "$TEMP_MIRRORLIST" | tee "$TEMP_MIRRORLIST.fastest" || exit 1
    fi

    [ "$DONT_REPLACE" = 1 ] && return
    print_header "Install new mirrorlist"
    if [ "$REPLACE" != 1 ]; then
        print_header "Replace current mirrorlist?"
        read -p "(y/N) " answer
        case $answer in
            y | Y | yes | Yes) ;;
            *) return ;;
        esac
    fi
    check_dependencies sudo
    sudo mv -v "$TEMP_MIRRORLIST.fastest" "${DEST:-/etc/pacman.d/mirrorlist}" || exit 1
    REPOS_UPDATED=1
}


# parse arguments
while :; do
    case $1 in
        -d | --dontreplace) DONT_REPLACE=1; shift ;;
        -e | --edit) EDIT=1; shift ;;
        -h | --help) print_help; exit ;;
        -m | --main) MAIN_ONLY=1; shift ;;
        -r | --replace) REPLACE=1; shift ;;
        *) break ;;
    esac
done

. /etc/os-release \
    || die "No OS information available"

REPOSITORY="$ID"

case $ID in
    manjaro)
        manjaro
        ;;
    artix)
        MIRRORURL="https://gitea.artixlinux.org/packagesA/artix-mirrorlist/raw/branch/master/trunk/mirrorlist"
        regular
        if [ "$MAIN_ONLY" != 1 ]; then
            REPOSITORY="arch"
            MIRRORURL="https://archlinux.org/mirrorlist/all/https/"
            DEST="${DEST:-/etc/pacman.d/mirrorlist}-arch"
            regular
        fi
        ;;
    arch)
        MIRRORURL="https://archlinux.org/mirrorlist/all/https/"
        regular
        ;;
    *)
        die "Your distro seems to not be supported ($NAME)"
        ;;
esac

if [ "$REPOS_UPDATED" = 1 ]; then
    print_header "Update Pacman database and packages"
    check_dependencies pacman sudo
    sudo pacman -Syyu
fi
